### PR TITLE
Use system() function (fix #16)

### LINKED ISSUE #16: Please use system() to suppress the screen flickering
In `s:open_url(url)`, you use `:silent! [command]` and redraw the screen. It causes the screen flickering. You can use the `system()` function to fix this issue.

### PR DESCRIPTION
**Pull request by itchyny**

### CODE REVIEW

**Comment by itchyny** [comment]
`silent! [cmd]` cannot suppress the error message of xdg-open. `system()` solves this issue.
screenshot from 2015-01-26 14 59 46

**Comment by junegunn** [comment]
Great job. Thanks!

**Comment by junegunn** [comment]
Notice that I removed `fnameescape` in that case, as it didn't work well with URL containing `#`.

**Comment by itchyny** [comment]
Fine, thanks for merging.

**Pull request merged**
